name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull techguyash/node-demo:latest
    - name: Delete Old docker container
      run: sudo docker rm -f node-demo-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name node-demo-container techguyash/node-demo